### ISSUE TITLE
ToDo List

### ISSUE THREAD

**Issue by GVBilokorenko** [Artem-Vladimirov-IP95/SaleTicket#1]
- [ ] Get rid of unnecessary ejs estension / back to html.

- [ ] Install Prettier, ESlint / code style changes.

- [ ] Get Mit license.

- [ ] Project Description.

- [ ] Contributors.
